version: "3.9"

services:
  renewsim-frontend:
    build: .
    container_name: renewsim-frontend
    ports:
      - "5174:5174"
    networks:
      - renewsim-net

  renewsim-backend:
    image: lannyrivero/renewsim-backend:latest
    container_name: renewsim-backend
    ports:
      - "8080:8080"
    networks:
      - renewsim-net

  cypress:
    build:
      context: .
      dockerfile: cypress.Dockerfile
    container_name: renewsim-cypress
    depends_on:
      - renewsim-frontend
      - renewsim-backend
    networks:
      - renewsim-net

networks:
  renewsim-net:

