name: Cypress E2E Tests

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Start the frontend
        run: npm run dev &
        env:
          NODE_ENV: production

      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:5174

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: http://localhost:5174





