name: Cypress E2E Tests

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.5
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers
        run: |
          docker-compose -f docker-compose.yml up -d --build
          sleep 10 # da tiempo a que los contenedores levanten

      - name: Run Cypress container
        run: |
          docker-compose -f docker-compose.yml run --rm cypress

      - name: Tear down containers
        run: docker-compose -f docker-compose.yml down -v


