name: Cypress E2E Tests

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build and start containers
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Wait for services to be ready
        run: sleep 20

      - name: Run Cypress tests
        run: docker-compose -f docker-compose.yml run --rm cypress

      - name: Stop containers
        run: docker-compose -f docker-compose.yml down



